"""add ad evaluations table

Revision ID: 4854c9bba5df
Revises: ac7d1c5d4ae6
Create Date: 2026-07-24 13:35:51.204326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4854c9bba5df'
down_revision: Union[str, Sequence[str], None] = 'ac7d1c5d4ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('slogan_quality_score', sa.Integer(), nullable=False),
    sa.Column('visual_quality_score', sa.Integer(), nullable=False),
    sa.Column('product_fidelity_score', sa.Integer(), nullable=False),
    sa.Column('strategy_alignment_score', sa.Integer(), nullable=False),
    sa.Column('slogan_visual_alignment_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['ad_drafts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ad_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_evaluations_draft_id'), 'ad_evaluations', ['draft_id'], unique=False)
    op.create_index(op.f('ix_ad_evaluations_id'), 'ad_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_ad_evaluations_project_id'), 'ad_evaluations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_evaluations_project_id'), table_name='ad_evaluations')
    op.drop_index(op.f('ix_ad_evaluations_id'), table_name='ad_evaluations')
    op.drop_index(op.f('ix_ad_evaluations_draft_id'), table_name='ad_evaluations')
    op.drop_table('ad_evaluations')
    # ### end Alembic commands ###
