"""remove reuse tone from ad strategies

Revision ID: bd3e5f6258bf
Revises: a86d8bf28ca9
Create Date: 2026-07-10 11:18:15.491564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3e5f6258bf'
down_revision: Union[str, Sequence[str], None] = 'a86d8bf28ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_strategies', 'reuse_tone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_strategies', sa.Column('reuse_tone', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
